"""Baut data/luebeck1395.json: der Lübecker Hansetag vom 29. September 1395 und Detmars Chronik (Auszüge).

Mittelniederdeutsch und Latein: Hanserecesse, 1. Abt., Bd. 4, hg. von Karl Koppmann (Leipzig 1877),
Nr. 308 (Rezess zu Lübeck, 29. September 1395), S. 303–305, und Nr. 309 (Zusatz der preußischen
Ratssendeboten, „Dyt sint dy artikele van dem Stokholme“), S. 305–306. Internet Archive
hanserecesse12roppgoog, Blatt = Seite + 41 (page/n<Blatt>_w3000.jpg).
Detmar: Die Chroniken der niedersächsischen Städte. Lübeck, Bd. 2 (Die Chroniken der deutschen Städte 26,
Leipzig 1899), §§ 974–975 (S. 50–51), § 1009 (S. 66) und § 1019 (S. 79–80, erste Fortsetzung).
Internet Archive bub_gb_oqgKAAAAIAAJ, Blatt = Seite + 26. Alles am Seitenbild gelesen.
Übersetzung: eigene Arbeitsübersetzung (CC0).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "luebeck1395.json"

DETMAR = [
    dict(n=1, titel="Ein steuerloses Volk", pg="Chron. 26 S. 50–51",
         orig="974. In deme sulven jare warp sik tosamende en sturlos volk von meniger jegen, van hoveluden, van borgeren ute velen steden, van amptluden, van buren, unde heten sik vitalienbroder. se spreken, se wolden teen up de koninghinnen van Denemarken to hulpe deme koninghe van Sweden, den see hadde gevangen, ene los tho ridende, unde se nemande nemen scolden noch beroven, sunder de dar sterkeden de koninghinnen mit gude edder mit hulpe. so bedroveden se leider de gansen see unde alle koplude, unde roveden, beide, uppe vrunt unde viande, also dat de Sconesche reise wart nedderlêget wol 3 jaar. dar umme was in den jaren de harink vůl dure.",
         en="974. Im selben Jahr rottete sich ein steuerloses Volk aus vielen Gegenden zusammen, von Hofleuten, von Bürgern aus vielen Städten, von Handwerkern, von Bauern, und nannte sich Vitalienbrüder. Sie sagten, sie wollten gegen die Königin von Dänemark ziehen, dem König von Schweden zu Hilfe, den sie gefangen hatte, um ihn freizukämpfen, und sie sollten niemanden berauben oder ausplündern als die, welche die Königin mit Gut oder mit Hilfe stärkten. So betrübten sie leider die ganze See und alle Kaufleute und raubten bei beiden, bei Freund und bei Feind, sodass die Schonenfahrt wohl drei Jahre daniederlag. Darum war in diesen Jahren der Hering sehr teuer.",
         note="Detmar, Lesemeister der Lübecker Franziskaner, schrieb seine Chronik im Auftrag des Rats; sie endet 1395 und ist hier die Stimme Lübecks. Er stellt die Stelle unter 1392. ‚Sturlos‘ heißt ohne Steuer, ohne Führung: ein Volk, das niemand lenkt. Die Aufzählung reicht vom Adel (‚hovelude‘) über Bürger und Handwerker (‚amptlude‘, Angehörige der Ämter) bis zu Bauern. Detmar übernimmt das Programm der Vitalienbrüder und misst sie daran: Sie sollten nur Margaretes Helfer berauben und raubten bei Freund und Feind. Die Schonenfahrt ist der Heringshandel auf Schonen, Lübecks wichtigstes Geschäft. Die lateinische Chronik Hermann Korners sagt deutlicher, wer sie rief: Rostock und Wismar hätten zur Befreiung Albrechts Räuber angeworben, ‚qui se Vitalianos nominabant‘."),
    dict(n=2, titel="Bergen", pg="Chron. 26 S. 51",
         orig="975. In deme sulven jare wůnnen de vitalienbroder Bergen in Norwegen, unde vele ander land vorhêrden se in Denemarken.",
         en="975. Im selben Jahr gewannen die Vitalienbrüder Bergen in Norwegen, und viele andere Lande in Dänemark verheerten sie.",
         note="Ein Satz für das größte Unternehmen der Vitalienbrüder. Bergen war das Kontor der Hanse in Norwegen; nach Angaben der Engländer, deren Kaufleute dort Schaden nahmen, fiel es am 22. April 1393, nicht 1392. Korner fügt hinzu, sie hätten einen ‚inestimabilem thezaurum‘ fortgeführt, einen unschätzbaren Schatz."),
    dict(n=3, titel="Zwanzig Schiffe unter vier Ratsherren", pg="Chron. 26 S. 66",
         orig="1009. In deme neghesten daghe des vorbenomeden festes do sanden de van Lubeke ut tho der zee wart 20 grote hovetschepe mit anderen schepen unde snycken unde mit vele weraftigen luden. den weren gheset veer hovetmanne ute deme rade, unde bleven in der zee bet na sunte Mycheles daghe, unde stureden, dat van den vitalienbroderen nyn schade en schach. unde also wurden de vitalienbroder ghekrenket.",
         en="1009. Am nächsten Tag nach dem genannten Fest sandten die von Lübeck 20 große Hauptschiffe zur See hinaus, mit anderen Schiffen und Schniggen und mit vielen wehrhaften Leuten. Über sie waren vier Hauptleute aus dem Rat gesetzt; sie blieben auf See bis nach St. Michaelis und wehrten, dass von den Vitalienbrüdern kein Schaden geschah. Und so wurden die Vitalienbrüder geschwächt.",
         note="Das genannte Fest ist Fronleichnam, 1395 der 10. Juni; die Flotte lief also am 11. Juni aus und blieb bis nach dem 29. September in See, bis zum Hansetag dieses Moduls. Vier Ratsherren als Hauptleute: Lübeck führt selbst. ‚Snicken‘, Schniggen, sind schnelle kleine Begleitschiffe. Eine Urkunde über diese Ausfahrt ist nicht erhalten. Der Herausgeber bezieht auf sie eine spätere Beschwerde der Lübecker Bürgerschaft (Lübeckisches Urkundenbuch 5, S. 184): ‚Item do de grote were in de zee ghemaket wart, dar de borghere do umme uppe grote koste gebrocht worden, unde synt der tyd verfaren is, dat men mit der were nicht doen moste.‘ Die Bürger wurden für die große Wehr zur See in schwere Kosten gebracht und erfuhren hinterher, dass man mit ihr nichts ausrichten durfte. Detmars ‚ghekrenket‘ und die Klage der Bürger sind zwei Bilanzen derselben Ausfahrt."),
]

TAG = [
    dict(n=1, titel="Wer am Michaelistag in Lübeck tagte", pg="HR I.4 S. 303", lang="la",
         orig="Anno Domini 1395 in festo beati Michaelis archangeli Lubeke ad placita congregati domini nuncii consulares civitatum infrascriptarum, videlicet: de Hamborch Kerstianus Miles et Johannes Hoyer; de Stralessundis Arnoldus de Soest; de Prussia: de Thorun Gotze Rebber; de Elbingo Johannes Stolte; de Livonia: (de Rivalia) Johannes Stoltevoet; de Mari meridiano: de Campen Johannes Schilder; de Davantria Hinricus van Leyden; de Zutphania Andreas de Yserne; de Herderwik Hildebrant van Telge(de)n; de Stoveren Otto Dodensone; de Lubeke domini Gerhardus de Attendorn, Thomas Murkerke, Hinricus Westhoff, Johannes Nyebur, Bertoldus Kerkringh et Hermannus Dartzowe, hec infrascripta pertractaverunt negocia.",
         en="Im Jahr des Herrn 1395, am Fest des heiligen Erzengels Michael, versammelten sich zu Lübeck zur Tagfahrt die Herren Ratssendeboten der unten geschriebenen Städte, nämlich: von Hamburg Christian Miles und Johannes Hoyer; von Stralsund Arnold von Soest; aus Preußen: von Thorn Gotze Rebber, von Elbing Johannes Stolte; aus Livland: von Reval Johannes Stoltevoet; von der Zuiderzee: von Kampen Johannes Schilder, von Deventer Hinrich van Leyden, von Zutphen Andreas de Yserne, von Harderwijk Hildebrant van Telgeden, von Stavoren Otto Dodensone; von Lübeck die Herren Gerhard von Attendorn, Thomas Murkerke, Hinrich Westhoff, Johannes Nyebur, Bertold Kerkring und Hermann Dartzow; und sie verhandelten die unten geschriebenen Geschäfte.",
         note="Der Rezess ist nach der Handschrift zu Ledreborg gedruckt, mit den Abweichungen der Thorner und der Hamburger Handschrift. Lübeck sendet sechs Ratsherren, jede andere Stadt einen oder zwei. Rostock und Wismar fehlen: Über sie wird verhandelt. Dortmund hatte abgesagt, wegen einer Fehde (Brief vor Nr. 308). Was eine solche Tagfahrt kostete, zeigen die Hamburger Kämmereirechnungen: 68 Pfund 6 Schilling für die beiden Hamburger, und 24 Schilling für zwei Pfund kandierten Zimt, als die Ratsherren von Deventer und Zutphen auf dem Weg durch Hamburg kamen. ‚Mare meridianum‘ ist die Zuiderzee."),
    dict(n=2, titel="Die Klagen gegen Rostock und Wismar", pg="HR I.4 S. 303",
         orig="1. Int erste sind gelesen vor den steden menigerleye breve, sunderkes des koninghes van Engeland, des heren van Moerse, des ghemenen kopmans van Brugghe in Vlandren, van Lunden in Engeland, dar se sik swarliken ynne beclaghen van mengerleye groten drapliken schaden, de den Engelschen und den Vlaminghen und dem menen kopmanne van der hense gescheen is van den van Rozstok und van der Wysmer, war umme de stede vorscreven ere muntlike boden mit eren credencienbreven gesant hadden tho den van Rozstoke und van der Wysmer, begherende, dat se ere vulmechtige boden hebben wolden by den steden vorscreven, umme tho sprekende, wes me den heren und dem kopmanne vorbenomet wedder vor en antworde scriven mochte, wente de here van Moerze, de Engelsche und de Vlamissche kopman eren schaden menen tho vorhalende uppe de ghemenen stede und kopman van der hense, se weren van wat steden, dat se weren.",
         en="1. Zuerst sind vor den Städten mancherlei Briefe gelesen worden, besonders vom König von England, vom Herrn von Moers und vom gemeinen Kaufmann zu Brügge in Flandern und zu London in England, in denen sie sich schwer beklagen über mancherlei großen, beträchtlichen Schaden, der den Engländern, den Flamen und dem gemeinen Kaufmann von der Hanse von denen von Rostock und von Wismar geschehen ist. Darum hatten die genannten Städte ihre Boten mit Beglaubigungsbriefen zu denen von Rostock und von Wismar gesandt und begehrt, sie möchten ihre bevollmächtigten Boten bei den genannten Städten haben, um zu besprechen, was man den genannten Herren und dem Kaufmann zur Antwort zurückschreiben könne. Denn der Herr von Moers und der englische und der flämische Kaufmann gedenken, ihren Schaden an den gemeinen Städten und Kaufleuten der Hanse zu erholen, aus welchen Städten sie auch seien.",
         note="Der Kern des Problems für den Lübecker Rat steht im letzten Satz. Wer in England oder Flandern geschädigt wurde, unterscheidet nicht zwischen Rostock und Lübeck: Er hält sich an jeden Hansekaufmann, dessen Gut er greifen kann. Die Kaperei zweier Bundesstädte bedroht so die Kontore in London und Brügge. Der Herr von Moers ist der Graf am Niederrhein."),
    dict(n=3, titel="Der König verteidigt seine Helfer", pg="HR I.4 S. 303–304",
         orig="2. Des geliik vel yd, dat der stad van Lubeke radissendeboden qwemen by koning Alberthe van Sweden tho daghe tho Reene, dar se eme dat werff mank andern reden ok vorstan leten. Des wart de koningh des tho rade, dat he, sin sone, sin rad mit den van Rozstoke und van der Wysmer qwemen by de stede vorscreven bynnen de stad tho Lubeke, dar de stede eme de vorscreven claghe vorstan leten, und dar he tho antworde, wes se dar ane daen hadden, dat hadden se gedan in sinen besten und umme syner losinghe willen, und bat de stede dar umme, dat se en dat tho nenen arghe keren wolden. War tho de stede antwerden, dat en des nicht stunde over tho gevende. Also dat mank velen reden, de dar an beyden siden over villen, de koningh begherende was van den steden, dat men dat mit den van Rozstok und van der Wismer wolde bestan laten also langhe, dat he dar vurder up denken mochte, und dat me eme des en antworde benalen wolde bynnen twen daghen. Doch so vel yd, dat eme dat antworde secht wart, eer dat he van hir reet, in desser wyse, wo dat de stede under sik enes daghes geramet hadden, tho holdende hir tho Lubeke up sunte Johannis dach tho middensomer negest komende: wolde he und de van Rozstok und van der Wysmer dar by komen, dat seghen se gherne; doch bynnen der tid den steden und dem menen kopmanne unvorsumet aller maninghe, de se tho en hebben.",
         en="2. Ebenso fügte es sich, dass die Ratssendeboten der Stadt Lübeck zu König Albrecht von Schweden auf einen Tag nach Rehna kamen, wo sie ihm unter anderen Reden auch diese Werbung vortrugen. Daraufhin beschloss der König, dass er, sein Sohn und sein Rat mit denen von Rostock und von Wismar zu den genannten Städten in die Stadt Lübeck kämen. Dort trugen ihm die Städte die genannte Klage vor, und er antwortete: Was jene dabei getan hätten, das hätten sie zu seinem Besten und um seiner Befreiung willen getan; und er bat die Städte, es ihnen nicht zum Argen zu kehren. Darauf antworteten die Städte, es stehe ihnen nicht zu, das zu erlassen. Unter vielen Reden, die dabei auf beiden Seiten fielen, begehrte der König von den Städten, man möge die Sache mit denen von Rostock und von Wismar so lange ruhen lassen, bis er weiter darüber nachdenken könne, und ihm binnen zwei Tagen eine Antwort geben. Doch fügte es sich, dass ihm die Antwort gesagt wurde, ehe er von hier ritt, in dieser Weise: Die Städte hätten untereinander einen Tag verabredet, hier in Lübeck auf St. Johannis zu Mittsommer nächstkünftig zu halten; wollten er und die von Rostock und von Wismar dazu kommen, das sähen sie gern. Doch solle bis dahin den Städten und dem gemeinen Kaufmann keine ihrer Forderungen an sie versäumt sein.",
         note="Albrecht, im Sommer durch den Frieden von Lindholm freigekommen, erscheint selbst in Lübeck, mit seinem Sohn, seinem Rat und den beiden Städten. Seine Verteidigung ist die der Kaperer: ‚umme syner losinghe willen‘, um seiner Befreiung willen. Die Städte antworten, die Forderungen seien nicht die ihren und darum nicht ihnen zu erlassen: Geschädigt sind Engländer, Flamen und der Kaufmann. Rehna liegt in Mecklenburg. Der nächste Tag ist auf den 24. Juni 1396 angesetzt; bis dahin bleibt alles offen. Detmars Fassung derselben Sache steht in Lübeck 1395 Detmar [1]."),
    dict(n=4, titel="Die See befrieden, zum zweiten Mal", pg="HR I.4 S. 304",
         orig="3. Item umme den groten drapliken schaden, de in menigerleye zeerove und morde van langhen tiden deme ghemenen kopmanne tho der zeewart gescheen is und noch schůt, so sint de stede hir tho desser dachvart vorgaddert des tho rade worden, dat se de zee willen bevreden vor den zeeroveren, also dat de kopman velich varen moghe, und malk dem andern dar truweliken wil tho helpen in desser wiis, also hir na screven steit: also dat de van Lubeke scholen utmaken twe schepe mit 200 werafftich, de van Prussen veer schepe mit 350 werafftich, de van dem Sunde 1 schip mit 100 werafftich, de van Liifflande en schip mit 100 werafftich, de van Hamborch en schip mit 50 werafftich, de van Campen und de ghemenen stede van der Suderzee, Hollant und Zeelant thosamende twe schepe mit 200 werafftich; also dat yo mank 100 werafftighen schollen wesen 30 schutten mit eren vullen wapene und mit starken armborsten, und en yewelik schip schal wesen mit ener snicken und mit ener schuten. Dit hefft en yewelik tho syneme rade toghen, den van Lubeke dar en antworde van tho enbedende. Und werit, dat se des tho rade worden, dat se dat doen wolden, so willet se sik vinden des sundaghes veirteindaghe na passchen, alse de van Lubeke, de van dem Sunde, de van der Suderzee und de van Hamborch scholen sik vinden tho Drakôre; we eer kumpt, dan de andere, de schal des andern beyden. Und wan se dar thosamende sint, so scholen se vort segelen tho Bornholme tho den van Prussen und tho den van Liiflande.",
         en="3. Item: Wegen des großen, beträchtlichen Schadens, der dem gemeinen Kaufmann seit langer Zeit auf der Seefahrt in mancherlei Seeraub und Mord geschehen ist und noch geschieht, sind die Städte, hier zu dieser Tagfahrt versammelt, übereingekommen, dass sie die See vor den Seeräubern befrieden wollen, sodass der Kaufmann sicher fahren könne, und jeder will dem andern dabei treulich helfen, in dieser Weise, wie hiernach geschrieben steht: Die von Lübeck sollen zwei Schiffe ausrüsten mit 200 Wehrhaften, die von Preußen vier Schiffe mit 350 Wehrhaften, die von Stralsund ein Schiff mit 100 Wehrhaften, die von Livland ein Schiff mit 100 Wehrhaften, die von Hamburg ein Schiff mit 50 Wehrhaften, die von Kampen und die gemeinen Städte von der Zuiderzee, Holland und Seeland zusammen zwei Schiffe mit 200 Wehrhaften; und zwar so, dass unter je 100 Wehrhaften 30 Schützen sein sollen, mit ihrer vollen Rüstung und mit starken Armbrüsten, und jedes Schiff soll eine Schnigge und eine Schute bei sich haben. Dies hat jeder an seinen Rat mitgenommen, um denen von Lübeck Antwort darauf zu entbieten. Und beschließen sie, es zu tun, so wollen sie sich am Sonntag vierzehn Tage nach Ostern einfinden: Die von Lübeck, von Stralsund, von der Zuiderzee und von Hamburg sollen sich bei Dragør einfinden; wer eher kommt als der andere, soll auf den andern warten. Und wenn sie dort beisammen sind, sollen sie weiter nach Bornholm segeln zu denen von Preußen und denen von Livland.",
         note="Derselbe Satz wie im März 1394, ‚de zee bevreden vor den zeeroveren‘ (Flotte 1394 [1]), aber eine viel kleinere Flotte: elf Schiffe mit tausend Mann statt über dreißig, und Lübeck stellt zwei statt sechs. Beschlossen ist nichts: Jede Stadt nimmt die Quote an ihren Rat zurück und antwortet Lübeck. Der Treffpunkt ist der Sonntag zwei Wochen nach Ostern 1396, der 16. April, bei Dragør auf Amager am Øresund; von dort geht es nach Bornholm zu Preußen und Livland. Die Hamburger Handschrift gibt in einer zweiten Spalte eine etwas andere Ordnung. Eine Schute ist ein Beiboot."),
    dict(n=5, titel="Preußen will das Pfundgeld, die Städte nicht", pg="HR I.4 S. 305",
         orig="11. Ok hebbet de sendeboden van Prussen worven vor den steden und weren begherende, dat de stede wolden puntgeld nemen tjeghent jar. Dar hebbet de stede umme sproken, und menen, dat en dat noch nicht nutte dunke wesen, und hebbet dar umme ere breve gescreven an de stede van Prussen, und hebben ok de sendeboden gebeden, dat se dat willen werven, alse hir na gescreven is: Folgt Nr. 313.",
         en="11. Auch haben die Sendeboten von Preußen vor den Städten geworben und begehrt, dass die Städte für das kommende Jahr Pfundgeld erheben sollten. Darüber haben die Städte gesprochen und meinen, es scheine ihnen noch nicht nützlich; darum haben sie ihre Briefe an die Städte von Preußen geschrieben und auch die Sendeboten gebeten, das so vorzutragen, wie hiernach geschrieben ist: [es folgt der Brief Nr. 313].",
         note="Diesmal will Preußen den Zoll auf die Ladung, mit dem 1394 die Friedeschiffe bezahlt wurden (Flotte 1394 Pfundgeld [1]), und die anderen Städte lehnen ab. Wer die Schiffe stellen soll, muss sie auch bezahlen; ohne Pfundgeld bleibt die Last bei jedem Rat selbst. Den Paragraphen hat nur die Ledreborger Handschrift."),
]

STOCKHOLM = [
    dict(n=1, titel="Geleit für die Vitalienbrüder des Königs", pg="HR I.4 S. 305",
         orig="4. Vortmer umme dy vitalienbruder, dy in des koningis were gelegen hebben und zodder dem vrede den kopman nicht beschediget hebben, eft dy scholen geleydet wesen: des is use meyninge, dat ghii dy gene, dy den kopman beschediget hebben, nicht en leyden; jodoch duchtet jw und der stat nůtte wesen, dat ghii sy leyden; und dat ghii des denne alzo rameden, dat ghii erer alzo lůttik leyden, dat it sůnder vare sy.",
         en="4. Ferner wegen der Vitalienbrüder, die im Dienst des Königs gelegen und seit dem Frieden den Kaufmann nicht geschädigt haben, ob die Geleit haben sollen: Unsere Meinung ist, dass ihr diejenigen, die den Kaufmann geschädigt haben, nicht geleitet; dünkt es euch und der Stadt aber nützlich, dass ihr sie geleitet, so sollt ihr es so einrichten, dass ihr ihrer so wenige geleitet, dass es ohne Gefahr sei.",
         note="Nr. 309 ist ein Zusatz der preußischen Ratssendeboten, überschrieben ‚Dyt sint dy artikele van dem Stokholme‘, und richtet sich an die Hauptleute, die Stockholm für die Städte als Pfand halten (Lindholm Stockholm). In der Stadt lagen Vitalienbrüder als Besatzung des Königs. Wer seit dem Frieden niemanden geschädigt hat, kann Geleit bekommen, also sicheres Abziehen; wer den Kaufmann geschädigt hat, nicht. Die Linie zwischen Helfer und Seeräuber verläuft hier am Friedensschluss. Das Seitenbild schneidet den linken Rand ab; einige Anfangsbuchstaben (‚und‘, ‚geleydet‘, ‚hebben‘, ‚leyden‘, ‚it‘) sind ergänzt."),
    dict(n=2, titel="Das verwüstete Land", pg="HR I.4 S. 306",
         orig="6. Vortmer umme dat land, dat vorwůstet is, und dy vorarmeden bůndere, dy dar uppe sint, eft man en schole hulpe don: dar scholen dy hovetlude des besten ane ramen, alze dat et sunder eren schaden sy.",
         en="6. Ferner wegen des Landes, das verwüstet ist, und der verarmten Bauern, die darauf sitzen, ob man ihnen Hilfe tun soll: Darin sollen die Hauptleute auf das Beste bedacht sein, so dass es ohne ihren Schaden sei.",
         note="‚Bůndere‘ ist das schwedische bönder, Bauern. Sechs Jahre Belagerung und Kaperkrieg haben das Land um Stockholm verwüstet. Helfen dürfen die Hauptleute, aber nur, wenn es die Städte nichts kostet."),
    dict(n=3, titel="Schiffe gegen die Vitalienbrüder", pg="HR I.4 S. 306",
         orig="7. Vortmer umme dy schepe dy vitalienbruder to vordryvende: dar hebben wy umme sproken, und wes wy dar ane to rade werden to donde, dat schal den hovetluden wol to wetende werden.",
         en="7. Ferner wegen der Schiffe, um die Vitalienbrüder zu vertreiben: Darüber haben wir gesprochen, und was wir darin zu tun beschließen, das soll den Hauptleuten gewiss zu wissen werden.",
         note="Dieselben Vitalienbrüder, denen § 4 unter Bedingungen Geleit gibt, sollen mit Schiffen vertrieben werden. Beschlossen ist auch hier noch nichts: Die Antwort steht in Lübeck 1395 Rezess [4], und sie war nur eine Vorlage für die Räte."),
    dict(n=4, titel="Der Königin nicht helfen", pg="HR I.4 S. 306",
         orig="9. Vortmer eft man der koningynnen schole hulpe don van deme Stokholme: des dungket uns nůtte, dat men dy were van deme slote nicht en krengke.",
         en="9. Ferner, ob man der Königin von Stockholm aus Hilfe tun soll: Uns dünkt nützlich, dass man die Wehr des Schlosses nicht schwäche.",
         note="Die Städte halten Stockholm als Pfand zwischen den beiden Parteien und dürfen keiner helfen, ohne das Pfand zu gefährden. Margarete hatte offenbar um Hilfe gebeten; die Antwort ist ein höfliches Nein. Das Verb ist dasselbe wie in Detmars Bilanz der Lübecker Ausfahrt: krenken, schwächen (Lübeck 1395 Detmar [3])."),
]

OSTEN = [
    dict(n=1, titel="Vierhundert segeln nach Osten", pg="Chron. 26 S. 79–80",
         orig="1019. In deme sulven jare nach der losinghe des koninghes van Sweden do vornemen de vitaligenbrodere, dat se up der ze nicht mer mochten roven. des worpen sik verhundert tosamende in schepe unde zeghelden vor de Růssen in dat water, dat dar hetet de Nu; dar nemen se altogroten rôf. ze wolden enen anderen wech theen wedder to lande, unde vorbisterden in deme mêr unde quemen to Undudeschen luden, de se nicht vornemen, der se vele dot sloghen unde nemen en ere spise unde ere quyk, dar se sik mede vodeden. se seghelden vort, dat se quemen under dat hilghe lant to den berghete to Kaspien, dar se ummetighen vele volkes seghen, unde ghisseden, dat dar weren de roden joden. se sloghen erer vele doet up dem ôvere, men se en dorsten nicht to en sprenghen up dat land, wente erer was to vele. nicht verne ok van der sulven jeghene vunden se wilde lude, bewassen alumme mit hare. so langhe seghelden se, wallende umme de werlt, dat se vunden enen Dudeschen man, de was untforet; de wisede se to weghe nach der kenninghe der sunnen. also quam de helfte wedder to lande nach jartiid; de ander helfte was vorstorven in stride unde in hunghere.",
         en="1019. Im selben Jahr, nach der Freilassung des Königs von Schweden, merkten die Vitalienbrüder, dass sie auf der See nicht mehr rauben konnten. Darum taten sich vierhundert in Schiffen zusammen und segelten vor die Russen in das Wasser, das dort die Newa heißt; dort machten sie allzu große Beute. Sie wollten einen anderen Weg zurück nach Hause ziehen, verirrten sich im Meer und kamen zu fremden, nicht deutschen Leuten, die sie nicht verstanden; von denen schlugen sie viele tot und nahmen ihnen ihre Speise und ihr Vieh, wovon sie sich nährten. Sie segelten weiter, bis sie unter das Heilige Land zu den Bergen von Kaspien kamen, wo sie ringsum viel Volk sahen, und meinten, das seien die Roten Juden. Sie schlugen viele von ihnen am Ufer tot, wagten aber nicht, zu ihnen an Land zu springen, denn es waren ihrer zu viele. Nicht weit von derselben Gegend fanden sie auch wilde Leute, überall mit Haaren bewachsen. So lange segelten sie, um die Welt irrend, bis sie einen deutschen Mann fanden, der verschleppt worden war; der wies ihnen den Weg nach dem Stand der Sonne. So kam die Hälfte nach Jahresfrist wieder heim; die andere Hälfte war im Kampf und im Hunger gestorben.",
         note="Mit diesem Paragraphen beginnt in der Handschrift eine andere Hand: die erste Fortsetzung Detmars, 1395–1399. Ihr Ausgangspunkt ist nüchtern, nach Albrechts Freilassung ist auf der Ostsee nichts mehr zu holen, und ein Raubzug zur Newa, in das Land von Nowgorod, ist denkbar. Der Rest ist Weltkarte und Legende: Die Roten Juden sind die eingeschlossenen Völker, die man hinter den Kaspischen Bergen glaubte und die am Ende der Zeit hervorbrechen sollten; behaarte wilde Leute kennt jede mittelalterliche Weltbeschreibung. Was der Chronist von den Vitalienbrüdern erzählt, ist schon hier keine Nachricht mehr, sondern Geschichte. ‚Untforet‘ heißt entführt. Korner hat dieselbe Erzählung lateinisch."),
]

doc = {
    "id": "luebeck1395",
    "titel": "Der Lübecker Hansetag vom September 1395, mit Detmar",
    "autor": "Die Ratssendeboten der Hansestädte; Detmar von Lübeck und sein Fortsetzer",
    "jahr": "1395",
    "sprache": "de",
    "orig_sprache": "gml",
    "pg_label": "",
    "quelle": "Hanserecesse. Die Recesse und andere Akten der Hansetage von 1256–1430, Bd. 4, bearb. von Karl Koppmann (Leipzig 1877), Nr. 308 (Rezess zu Lübeck, 29. September 1395), S. 303–305, und Nr. 309 (Zusatz der preußischen Ratssendeboten), S. 305–306 (Internet Archive: hanserecesse12roppgoog). Detmar-Chronik in: Die Chroniken der niedersächsischen Städte. Lübeck, Bd. 2, hg. von Karl Koppmann (Die Chroniken der deutschen Städte 26, Leipzig 1899), §§ 974–975, 1009, 1019, S. 50–51, 66, 79–80 (Internet Archive: bub_gb_oqgKAAAAIAAJ). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Zwei Lübecker Blicke auf das Jahr 1395. Der Rezess des Hansetags am Michaelistag zeigt den Rat bei der Arbeit: Klagen aus England und Flandern gegen Rostock und Wismar, König Albrecht, der seine Helfer verteidigt, eine zweite, kleinere Friedeflotte, die erst noch die Räte passieren muss, und der Streit ums Pfundgeld. Dazu die Artikel der Preußen für die Hauptleute in Stockholm. Detmar, der Chronist des Rats, erzählt, woher die Vitalienbrüder kamen und wie Lübeck im Sommer 1395 allein in See ging; sein Fortsetzer macht aus ihrem Ende schon eine Legende. Mittelniederdeutsch nach den Drucken, am Seitenbild gelesen; Auslassungen sind mit […] bezeichnet, die Seitenangaben nennen den Druck.",
    "sections": [
        {"id": "detmar", "titel": "Detmars Chronik", "zk": "Lübeck 1395 Detmar",
         "blurb": "Der Chronist des Lübecker Rats über die Vitalienbrüder: woher sie kamen, was sie versprachen, Bergen, und die zwanzig Schiffe, mit denen Lübeck im Sommer 1395 allein in See ging.",
         "units": DETMAR},
        {"id": "tag", "titel": "Der Rezess vom Michaelistag", "zk": "Lübeck 1395 Rezess",
         "blurb": "Der Hansetag vom 29. September 1395: wer kam, was England und Flandern klagten, wie König Albrecht seine Helfer verteidigte, die zweite Friedeflotte und das Pfundgeld, das Preußen wollte.",
         "units": TAG},
        {"id": "stockholm", "titel": "Die Artikel von Stockholm", "zk": "Lübeck 1395 Stockholm",
         "blurb": "Was die Preußen den Hauptleuten in Stockholm raten: Geleit nur für Vitalienbrüder, die seit dem Frieden stillgehalten haben, Hilfe für die Bauern nur ohne Kosten, und keine Hilfe für die Königin.",
         "units": STOCKHOLM},
        {"id": "osten", "titel": "Die Fahrt nach Osten", "zk": "Lübeck 1395 Fortsetzung",
         "blurb": "Detmars Fortsetzer: Vierhundert Vitalienbrüder segeln an die Newa und geraten bis zu den Roten Juden am Kaspischen Gebirge. Eine erste Legende.",
         "units": OSTEN},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("luebeck1395.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
