"""Baut data/lindholm.json: der Frieden von Lindholm 1395 und Stockholm als Pfand der Städte (Auszüge).

Mittelniederdeutsch: Hanserecesse, 1. Abt., Bd. 4, hg. von Karl Koppmann (Leipzig 1877),
Nr. 261 (Rezess zu Skanör und Falsterbo, um 20. Mai 1395), S. 248–254, und Nr. 264
(Denkelbrief, [17. Juni 1395]), S. 258–259. Internet Archive hanserecesse12roppgoog,
Blatt = Seite + 41 (page/n<Blatt>_w3000.jpg). Am Seitenbild gelesen.
Übersetzung: eigene Arbeitsübersetzung (CC0).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "lindholm.json"

FRIEDE = [
    dict(n=1, titel="Ein Frieden auf drei Bedingungen", pg="249",
         orig="2. Und also des tovorn geramet was, dat men den vrede unde sone tovorn scholde vorwissen, dar umme is de koninginne gevraget, wo dat de vrede scholde luden. Dar heft se aldus tho geantwerdet: dat se den koning wil den steden to borghe doen uppe dryerleye stucke, dar umme moste de vrede ok stan uppe dren stucken; (wente) werit also, dat de koning und sin sone wedder inqwemen, so scholde de vrede stan 9 weken vor up to seggende; werit also, dat he er dat gelt gheve, so scholde de vrede stan en jar vor up tho seggende; werit aver also, dat er de Stokholm geantwort worde, so scholdet en stede sone blyven.",
         en="2. Und da zuvor vereinbart war, dass man Frieden und Sühne vorher sichern solle, ist die Königin gefragt worden, wie der Frieden lauten solle. Darauf hat sie so geantwortet: Sie wolle den König den Städten auf dreierlei Bedingungen hin gegen Bürgschaft überlassen; darum müsse auch der Frieden auf drei Bedingungen stehen. Denn wenn der König und sein Sohn wieder in die Haft zurückkämen, so solle der Frieden neun Wochen vor seiner Aufkündigung gelten; wenn er ihr das Geld gäbe, so solle der Frieden ein Jahr vor der Aufkündigung gelten; würde ihr aber Stockholm übergeben, so solle es eine beständige Sühne bleiben.",
         note="Königin Margarete von Dänemark und Norwegen hielt seit der Schlacht von Falköping (1389) König Albrecht von Schweden und seinen Sohn Erich gefangen. Der Frieden hängt am Schicksal Stockholms: Erst wenn die Stadt an Margarete fällt, ist der Krieg zu Ende. ‚To borghe doen‘: den König freilassen, wofür andere bürgen."),
    dict(n=2, titel="Visby: das Land der Königin, die Stadt dem König", pg="249",
         orig="4. Umb de stad Wysbů, de wolde de koniginne yo tovoren wedder hebben to deme lande; doch umb bede und leve willen der sendeboden, so heft se des gevolget, dat dat land schal bliven to der koninginnen hant und erer, unde de stad to des koninghes hand, uppe recht; und werit also, dat sine hulpere wes van dem lande bekreftiget hadden vor sunte Juries daghe in dessem jare, dat scholde bliven by der stad, ok uppe recht; men wes se hebben bekreftiget na sunte Juries daghe, dat schal men myner vruwen wedder antwerden.",
         en="4. Wegen der Stadt Visby: die wollte die Königin unbedingt zuvor mit dem Land zurückhaben; doch auf Bitte und aus Liebe der Sendeboten hat sie eingewilligt, dass das Land in der Hand der Königin und der Ihren bleiben soll und die Stadt in der Hand des Königs, vorbehaltlich des Rechts; und hätten seine Helfer vor dem St.-Georgs-Tag dieses Jahres etwas vom Land in Besitz genommen, so soll das bei der Stadt bleiben, ebenfalls vorbehaltlich des Rechts; was sie aber nach dem St.-Georgs-Tag in Besitz genommen haben, das soll man meiner Herrin zurückgeben.",
         note="Visby auf Gotland war 1394 in die Hand der Vitalienbrüder gefallen, die hier als ‚Helfer‘ des Königs erscheinen. Die Stadt bleibt beim König, also bei ihnen; aus dieser Regelung wird ihr Stützpunkt bis 1398. Der St.-Georgs-Tag ist der 23. April."),
    dict(n=3, titel="Drei Jahre Frist, und wer das Risiko trägt", pg="249",
         orig="6. Alse tovorn geramet was, dat myn vruwe wolde den koning und sinen sone den steden tho borghe doen, und wolde en ên halff jar dach geven, des duchte des koninges rade de dach alto kort wesen. Dar umme hebben de sendeboden myne vruwen also hoch gebeden, dat se en wil dach geven van desser tiid an bet tho sunte Michels daghe und vort dree jar al umme mit alsulken vorworden: ist also, dat se willen dach hebben en halff jar, so schal dat eventur stan up myne vruwen, nicht uppe de borghen [...]; ist aver also, dat se willen dach hebben de dree jar al umme, so schal dat eventur und vaar stan uppe de borghen, nicht up myne vruwen, in desser wiis: werit also, dat erer en storve binnen der tiid, so scholde de andre alle degedinge holden, alse de begrepen sin, men storven se bynnen der tid beyde, so scholde men myner vruwen dat gelt geven edder den Stokholm antwerden.",
         en="6. Da zuvor vereinbart war, dass meine Herrin den König und seinen Sohn den Städten gegen Bürgschaft überlassen und ihnen ein halbes Jahr Frist geben wolle, schien den Räten des Königs die Frist allzu kurz. Darum haben die Sendeboten meine Herrin so dringend gebeten, dass sie ihnen Frist geben will von jetzt an bis zum St.-Michaels-Tag und weitere drei volle Jahre, mit folgenden Bedingungen: Wollen sie ein halbes Jahr Frist haben, so soll das Wagnis bei meiner Herrin liegen, nicht bei den Bürgen [...]; wollen sie aber die drei vollen Jahre Frist haben, so soll Wagnis und Gefahr bei den Bürgen liegen, nicht bei meiner Herrin, in dieser Weise: Stürbe einer von ihnen in dieser Zeit, so solle der andere alle Vereinbarungen halten, wie sie gefasst sind; stürben aber beide in dieser Zeit, so solle man meiner Herrin das Geld geben oder Stockholm übergeben.",
         note="Die Frist läuft bis Michaelis 1398 (29. September). Mit den drei Jahren übernehmen die Städte das Risiko: sterben König und Sohn, müssen sie zahlen oder Stockholm ausliefern. Ausgelassen ist die Regelung für das halbe Jahr. ‚Myn vruwe‘, meine Herrin, ist die Königin, so wie ihre Leute sie nennen; der Rezess übernimmt ihre Sprache."),
    dict(n=4, titel="Der Frieden zu Lindholm", pg="250",
         orig="8. Vortmer umme desse deghedinghe tho volghende und wul to teende, so reden de sendeboden tho deme Lintholme. Dar wart vor deme koninghe und syneme sone, vor der koninginnen und vor erem rade, in beydent siden up de vorscreven degedinge en vrede begrepen, de in beydent siden wart bejawordet und bebrevet in dem lude, alse hir na gescreven steit. [...] 9. Desse vorscreven vredebreve sint vor dem koninge und der koninginnen und eren radgeven gelesen und bejawordet in beiden siden, und besegelt van den vorsten, ertzebisscopen und bisscopen, ridderen, knapen und steden vorscreven in beiden siden.",
         en="8. Ferner: Um diese Verhandlungen weiterzuführen und zu vollenden, ritten die Sendeboten nach Lindholm. Dort wurde vor dem König und seinem Sohn, vor der Königin und vor ihrem Rat, auf beiden Seiten auf die genannten Verhandlungen hin ein Frieden geschlossen, der auf beiden Seiten bejaht und verbrieft wurde mit dem Wortlaut, wie hiernach geschrieben steht. [...] 9. Diese genannten Friedensbriefe sind vor dem König und der Königin und ihren Räten verlesen und auf beiden Seiten bejaht worden, und besiegelt von den Fürsten, Erzbischöfen und Bischöfen, Rittern, Knappen und Städten auf beiden Seiten.",
         note="Lindholm ist eine Burg in Schonen, wo Albrecht gefangen saß. Ausgelassen ist der Verweis auf den Friedensbrief (Nr. 262), den drei Erzbischöfe und neun Bischöfe für die Königin besiegelten; die mecklenburgische Seite besiegelte einen gleichlautenden (Nr. 263). Die Stralsunder und Danziger Fassung des Rezesses fasst den Paragraphen kürzer und vermerkt: ‚dar de konyng yeghenwardich was‘, wobei der König zugegen war."),
]

SEE = [
    dict(n=1, titel="Der Frieden beginnt sofort", pg="258–259",
         orig="Wanner dat nu alle degedinge, de hir gedegedinget sin, vulgetogen werden und de breve gesad unde bejawordet werden in beiden siden, so schal de vrede van staden an anstan mit al den yenen, de hir jegenwardich sind, und [men] schal dat von staden an enbeden, beyde to lande und tho watere, dat se in beiden siden vrede holden scholen. Und weme dat to wetende wert und darenboven den vrede breke, dar schal men over richten, alse de vredebreff utwiset.",
         en="Wenn nun alle Verhandlungen, die hier verhandelt sind, vollzogen sind und die Briefe auf beiden Seiten gesetzt und bejaht sind, so soll der Frieden sofort beginnen mit all denen, die hier anwesend sind, und man soll sofort gebieten, zu Lande und zu Wasser, dass sie auf beiden Seiten Frieden halten sollen. Und wem das kundgetan wird und wer darüber hinaus den Frieden bricht, über den soll man richten, wie es der Friedensbrief ausweist.",
         note="Ein ‚Denkelbrief‘ ist eine Merkurkunde: Der Text wurde dreimal auf ein Blatt geschrieben und auseinandergeschnitten; je ein Stück erhielten der König, die Königin und Lübeck für die Städte (so der Rezess, § 9). Koppmann datiert ihn auf den 17. Juni 1395."),
    dict(n=2, titel="Wer in der See ist, soll sie räumen", pg="259",
         orig="Und de yene, de in der zee sind, de scholen de zee rumen van staden an, wen en dat tho wetende wert, sunder argeliist. Wert, dat yemend darenboven den vrede breke edder den kopman beschedigede, to lande edder to watere, dar schal men over richten, alse vorscreven ys. Jodoch schal nemand in der zee bliven mit willen, alse verre, alse he wedder und wynd hefft, na sunte Jacobs dage negest to komende. Worde dar na yemand in der zee begrepen, de van dessem bode nicht holden en wolde, dar schal men over richten, alse vorscreven ys.",
         en="Und diejenigen, die in der See sind, sollen die See sofort räumen, sobald es ihnen kundgetan wird, ohne Arglist. Bräche jemand darüber hinaus den Frieden oder schädigte den Kaufmann, zu Lande oder zu Wasser, über den soll man richten, wie oben geschrieben ist. Jedoch soll niemand nach dem nächsten St.-Jakobs-Tag willentlich in der See bleiben, soweit er Wetter und Wind hat. Würde danach jemand in der See ergriffen, der dieses Gebot nicht halten wollte, über den soll man richten, wie oben geschrieben ist.",
         note="Das ist der Satz, der aus Kaperern Seeräuber macht. Wer bis zum St.-Jakobs-Tag, dem 25. Juli 1395, nicht heimkehrt, steht außerhalb des Friedens; ‚richten‘ heißt hier: hinrichten. ‚Alse verre, alse he wedder und wynd hefft‘: Nur wer wegen Wetter und Wind nicht heimkommt, ist entschuldigt."),
    dict(n=3, titel="Rostock, Wismar, Visby und Stockholm schließen ihre Häfen", pg="259",
         orig="Ok scholen de van Rozstok, van der Wismer, van Wysbu und van dem Stokholme ere havene, wen se to hus komen, van staden an tosluten, und dar nemande udlaten, de de koninginnen edder den kopman beschedege, sunder arch, to lande und to watere; und werit, dat dar yement, de van buten tho inqueme, de dessen vrede geholden hadde, de schal dar ynne bliven, und heft he den vrede broken na der tiid, dat eme dat bot tho wetene worden is, so schal men dar over richten.",
         en="Auch sollen die von Rostock, von Wismar, von Visby und von Stockholm ihre Häfen, wenn sie nach Hause kommen, sofort schließen und niemanden auslassen, der die Königin oder den Kaufmann schädigen könnte, ohne Arglist, zu Lande und zu Wasser; und wäre es so, dass jemand von draußen einliefe, der diesen Frieden gehalten hätte, der soll dort drinnen bleiben; und hat er den Frieden gebrochen, nachdem ihm das Gebot kundgetan worden ist, so soll man über ihn richten.",
         note="Die vier Häfen sind genau die Stützpunkte der Vitalienbrüder: Rostock und Wismar, aus denen sie ausliefen, Stockholm, das sie versorgten, und Visby, das sie hielten. Wer heimkehrt und den Frieden gehalten hat, darf bleiben; wer ihn brach, wird gerichtet. Ob Visby das tat, zeigt das Modul über Gotland 1398."),
]

STOCKHOLM = [
    dict(n=1, titel="Sechs Kirchspiele und zweitausend Mark", pg="252",
         orig="19. Item hefft de koning und de koninginne den seven steden, de den Stokholm scholen innemen, gevulbordet, de wyle dat se den Stokholm ynne hebben, to beholdende 6 kerspel, de dar tho beleghen sin, alze Negelinge und dat dar tho beleghen is, mit aller nutticheit tho brukende tho eren kosten. Dar tho schal de koninginne den steden geven alle jar 2000 marc Lubesch, alse desse nascreven breff ynneholt.",
         en="19. Item haben der König und die Königin den sieben Städten, die Stockholm einnehmen sollen, bewilligt, solange sie Stockholm innehaben, sechs Kirchspiele zu behalten, die dazu gehören, nämlich Näglinge und was dazugehört, mit allem Nutzen zu ihren Kosten zu gebrauchen. Dazu soll die Königin den Städten jedes Jahr 2000 Mark lübisch geben, wie dieser nachgeschriebene Brief enthält.",
         note="Die sieben Städte sind Lübeck, Stralsund, Greifswald, Thorn, Elbing, Danzig und Reval (Rezess § 12). Sie nehmen Stockholm als Pfand in Verwahrung, bis Albrecht zahlt oder die Stadt an Margarete fällt. Den Unterhalt tragen beide Kriegsparteien: das Land bewilligen König und Königin gemeinsam, das Geld gibt die Königin."),
    dict(n=2, titel="Rostock und Wismar zahlen für den König", pg="252",
         orig="20. Ok scholen de vorbenomeden seven stede van des koninghes weghen alle jar tho hulpe hebben 2000 marc, den Stokholm mede tho holdende. [...] De van Rozstok und van der Wysmer scholen den seven steden tho hulpe, den Stokholm mede tho holdende, van des koninghes weghen geven 3000 marc Lubesch. Dar van scholen se den steden up yslike hochtid to paschen bynnen den dren jaren negest volgende betalen dusent mark [...]. Werit aver also, dat eme Got hulpe, dat he den Stokholm losede, so scholen de stede den Stokholm nicht van sik antworden, de dree dusent mark syn en betalet.",
         en="20. Auch sollen die genannten sieben Städte von des Königs wegen jedes Jahr 2000 Mark zur Hilfe haben, um Stockholm damit zu halten. [...] Die von Rostock und von Wismar sollen den sieben Städten zur Hilfe, um Stockholm zu halten, von des Königs wegen 3000 Mark lübisch geben. Davon sollen sie den Städten an jedem Osterfest in den nächsten drei Jahren tausend Mark bezahlen [...]. Wäre es aber so, dass Gott ihm hülfe, dass er Stockholm auslöste, so sollen die Städte Stockholm nicht aus der Hand geben, bevor ihnen die dreitausend Mark bezahlt sind.",
         note="Rostock und Wismar, die Häfen der Vitalienbrüder, zahlen nun für die Verwahrung Stockholms, das die Vitalienbrüder versorgt hatten. Die Städte behalten das Pfand, bis jede Mark bezahlt ist."),
    dict(n=3, titel="Wer die Last trägt", pg="253",
         orig="26. Item hebben de sendeboden vorbenomed over en gedreghen van der utborginge des koninghes und ynneminghe des Stokholmes, also dat de(r) stede dre, Lubeke, Stralessunt, Gripeswolt, van allen lofften, teringhe und schaden de helffte der eventure scholen stan, und de stede van Prussen und Revele de andern helffte, sunder argeliist. [...] 28. Item off de erbenomeden stede vorder koste deden, den se van dem koninghe und koninginnen hebben, und dar umme puntgelt worde gesat up den ghemenen kopman, dat schal en ok in beiden siden gelik tho hulpe komen.",
         en="26. Item sind die genannten Sendeboten über die Bürgschaft für den König und die Einnahme Stockholms übereingekommen, dass von allen Gelöbnissen, Zehrung und Schaden die drei Städte Lübeck, Stralsund und Greifswald die Hälfte des Wagnisses tragen sollen und die Städte von Preußen und Reval die andere Hälfte, ohne Arglist. [...] 28. Item: Hätten die genannten Städte weitere Kosten, als sie vom König und von der Königin erhalten, und würde deswegen ein Pfundgeld auf den gemeinen Kaufmann gesetzt, so soll ihnen das auf beiden Seiten gleich zugutekommen.",
         note="Die Hanse teilt sich in zwei Hälften: die Wendischen Städte um Lübeck und die preußisch-livländischen. Reicht das Geld der Kronen nicht, zahlt wieder der Kaufmann, über ein Pfundgeld wie 1394 (Flotte 1394 Pfundgeld [1])."),
    dict(n=4, titel="Die Besatzung", pg="253",
         orig="29. Und de vorbenomeden dre stede, alse Lubeke, Stralessunt, Gripeswolt, scholen de helffte der lude und der were, den Stokholm tho holdende, untrichten, de van Prussen und Revele de andern helffte. Tho dem ersten schal yslik helffte dar senden 40 gude wepener mit platen und mit vullen harnssche und 30 gude schutten mit armborsten und mit wapen, alse dar tho horet. Item schal yslike helfte dar bringen 6 tunnen stotelen, veer steenbussen, 6 loetbussen und alse vele pulvers, alse men dar tho bedarff, und dar tho 30 gude armborste overich, wyppen und wynden. Item schal yslike helffte mede nemen enen guden bussenmeister und enen armborsterer; ok schal men mede nemen grote slote und heelden.",
         en="29. Und die genannten drei Städte, Lübeck, Stralsund und Greifswald, sollen die Hälfte der Leute und der Wehr stellen, um Stockholm zu halten, die von Preußen und Reval die andere Hälfte. Zuerst soll jede Hälfte dorthin 40 gute Bewaffnete mit Plattenrüstung und vollem Harnisch senden und 30 gute Schützen mit Armbrüsten und mit Waffen, wie es dazugehört. Item soll jede Hälfte dorthin bringen sechs Tonnen Armbrustbolzen, vier Steinbüchsen, sechs Lotbüchsen und so viel Pulver, wie man dazu braucht, und dazu 30 gute Armbrüste über den Bedarf, mit Wippen und Winden. Item soll jede Hälfte einen guten Büchsenmeister und einen Armbrustmacher mitnehmen; auch soll man große Schlösser und Fußfesseln mitnehmen.",
         note="140 Mann für eine Hauptstadt. ‚Stotelen‘ sind wohl Armbrustbolzen, ‚steenbussen‘ Steinbüchsen, Geschütze, die Steinkugeln schossen, ‚loetbussen‘ kleinere Büchsen, die Bleikugeln schossen. ‚Heelden‘ sind Fußfesseln: Die Besatzung rechnet mit Gefangenen."),
    dict(n=5, titel="Speck, Bier und Mandeln", pg="253–254",
         orig="Item is geramet, dat de van Lubeke, vamme Sunde und de van dem Gripeswolde scholen schicken in dat gemene to beiden delen 20 schippunt speckes, halff vet, halff magher. Vortmer 20 leste Lubesches und Sundesches beers und 10 leste Wysmers beyrs, item 5 leste Travensoltes, 1 pipen bomoleyes, 2 vate manoleyes, 2 balen rises, en balen mandelen, ½ last senepes, 600 Bergervissches und heringes. Wat dat kostet, dat scholen se wedder nemen van dem ersten gelde, dat de koningh, edder dat de van Rozstok und van der Wismer betalet. Item scholen de van Prussen int gemene kopen 30 leste roggen, 10 leste roggensmeels, 300 weytens, 3 leste erwete, 3 leste gorte, 40 leste moltes und also vele hoppen, alse men dar tho bedarff.",
         en="Item ist vereinbart, dass die von Lübeck, von Stralsund und von Greifswald für beide Teile gemeinsam 20 Schiffpfund Speck schicken sollen, halb fett, halb mager. Ferner 20 Last lübisches und sundisches Bier und 10 Last Wismarer Bier, item 5 Last Travesalz, eine Pipe Baumöl, zwei Fass Mohnöl, zwei Ballen Reis, einen Ballen Mandeln, eine halbe Last Senf, 600 Bergenfisch und Heringe. Was das kostet, sollen sie vom ersten Geld zurücknehmen, das der König oder die von Rostock und Wismar bezahlen. Item sollen die von Preußen gemeinsam 30 Last Roggen kaufen, 10 Last Roggenmehl, 300 Weizen, drei Last Erbsen, drei Last Grütze, 40 Last Malz und so viel Hopfen, wie man dazu braucht.",
         note="Die Liste zeigt, womit eine Garnison des späten 14. Jahrhunderts lebte: Speck, Bier (Wismarer Bier eigens genannt), Salz von der Trave, Stockfisch aus Bergen. Reis, Mandeln und Baumöl, also Olivenöl, kamen über Brügge aus dem Süden. Die Rechnung zahlen wieder die Häfen der Vitalienbrüder. ‚Bergervissch‘ ist Stockfisch aus Bergen. Bei ‚300 weytens‘ fehlt im Druck die Maßeinheit."),
]

doc = {
    "id": "lindholm",
    "titel": "Lindholm 1395 und Stockholm als Pfand",
    "autor": "Die Sendeboten des Hochmeisters und der Hansestädte, Königin Margarete und König Albrecht",
    "jahr": "1395",
    "sprache": "de",
    "orig_sprache": "gml",
    "pg_label": "HR I.4 S.",
    "quelle": "Hanserecesse. Die Recesse und andere Akten der Hansetage von 1256–1430, Bd. 4, bearb. von Karl Koppmann (Leipzig 1877), Nr. 261 (Rezess zu Skanör und Falsterbo, um 20. Mai 1395), S. 248–254, und Nr. 264 (Denkelbrief, [17. Juni 1395]), S. 258–259 (Internet Archive: hanserecesse12roppgoog). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Der Rezess der Verhandlungen zu Skanör und Falsterbo um Christi Himmelfahrt 1395 (20. Mai), gedruckt nach der Handschrift zu Ledreborg mit den Lesarten der Stralsunder und Danziger, und der Denkelbrief über den Beginn des Friedens, den Koppmann auf den 17. Juni datiert. Zwischen Margarete und Albrecht vermittelten die Sendeboten des Deutschen Ordens und der Städte; der Frieden wurde auf der Burg Lindholm in Schonen geschlossen. Die Auszüge folgen Koppmanns Text; Auslassungen sind mit [...] bezeichnet, runde Klammern bezeichnen seine Ergänzungen aus anderen Handschriften.",
    "sections": [
        {"id": "friede", "titel": "Der Frieden", "zk": "Lindholm Frieden",
         "blurb": "Der Frieden auf drei Bedingungen, Visby in der Hand des Königs, drei Jahre Frist bis Michaelis 1398 auf das Risiko der bürgenden Städte, und der Abschluss zu Lindholm.",
         "units": FRIEDE},
        {"id": "see", "titel": "Die See räumen", "zk": "Lindholm Denkelbrief",
         "blurb": "Der Denkelbrief: Der Frieden gilt sofort; wer in der See ist, soll sie räumen, und wer nach dem St.-Jakobs-Tag noch dort gefasst wird, wird gerichtet. Rostock, Wismar, Visby und Stockholm schließen ihre Häfen.",
         "units": SEE},
        {"id": "stockholm", "titel": "Stockholm als Pfand", "zk": "Lindholm Stockholm",
         "blurb": "Sieben Städte nehmen Stockholm in Verwahrung: wovon die Besatzung lebt, wer zahlt, wie sie sich die Last teilen, und was sie mitbringen, von Steinbüchsen bis zu Mandeln.",
         "units": STOCKHOLM},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("lindholm.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
